TEST:
  BATCH_SIZE: 64

OPTIM:
  METHOD: Adam
  STEPS: 1
  BETA: 0.9
  LR: 1e-3
  WD: 0.

INPUT:
  SIZE: (32, 32)

ADAPTER:
  NAME: mytta

  RoTTA:
    MEMORY_SIZE: 32
    UPDATE_FREQUENCY: 32
  
  PETTA:
    ALPHA_0: 0.001
    LAMBDA_0: 10.0
    REGULARIZER: "cosine"
    ADAPTIVE_LAMBDA: True
    ADAPTIVE_ALPHA: True
    NORM_LAYER: "rbn"
  
  MYTTA:
    MAX_MEMORY_BANKS: 5
    SEL_TOPK_BANKS: 5
    BASE_THRESHOLD: 0.3
    ALPHA_0: 0.001
    LAMBDA_0: 10.0
    REGULARIZER: "cosine"
    ADAPTIVE_LAMBDA: True
    ADAPTIVE_ALPHA: True
    NORM_LAYER: "rbn"
    ANCHOR_WGT: 1.0
    
LOADER:
  SAMPLER:
    TYPE: "class_temporal"
    # TYPE: "cgs"