MODEL:
  ARCH: Hendrycks2020AugMix_ResNeXt

TTA_DATA_DIR: /home/ywt/research/25-NeurIPS-TTA/datasets/CIFAR-100
SRC_DATA_DIR: /home/ywt/research/25-NeurIPS-TTA/datasets/CIFAR-100

CORRUPTION:
  DATASET: cifar100c_recur
  RECUR: 10
  CGS: True
  NUM_CLASS: 100
  SEVERITY:
    - 5
  TYPE:
    - motion_blur
    - snow
    - fog
    - shot_noise
    - defocus_blur
    - contrast
    - zoom_blur
    - brightness
    - frost
    - elastic_transform
    - glass_blur
    - gaussian_noise
    - pixelate
    - jpeg_compression
    - impulse_noise