TEST:
  BATCH_SIZE: 64

OPTIM:
  METHOD: Adam
  STEPS: 1
  BETA: 0.9
  LR: 1e-3
  WD: 0.

INPUT:
  SIZE: (32, 32)

ADAPTER:
  NAME: mytta

  PETTA:
    ALPHA_0: 0.001
    LAMBDA_0: 10.0
    REGULARIZER: "cosine"
    ADAPTIVE_LAMBDA: True
    ADAPTIVE_ALPHA: True
    NORM_LAYER: "rbn"
  
  MYTTA:
    STMEM_CAPACITY: 32
    STMEM_MAX_CLUS: 5
    STMEM_TOPK_CLUS: 5
    BASE_THRESHOLD: 0.3
    
LOADER:
  SAMPLER:
    TYPE: "class_temporal"
    # TYPE: "cgs"